### PR TITLE
2.0 Features

### LINKED ISSUE #6: Incorrect terminology around circuit breaking
Right now when a circuit is broken it registers it as being `closed`, and when a circuit is still viable it registers it as `open`. These are backwards. The terminology should be changed such that:

`open`: requests automatically fail and and circuit is tripped
`closed`: requests are properly flowing through to the request function passed

### PR DESCRIPTION
**Pull request by awolden**
This is a major pull request that handles a bunch of outstanding issues and feature improvements:

* Fixes terminology errors regarding open vs closed #6 
* Improves stat generation time, which in general increases the performance of the module
* Added a global stats tracker. Mainly to support hystrix dashboard integration
* Fixed an edge case that made stats reporting appear inaccurate #10 
* Added support for the naming and grouping of circuit breakers #7 
* Added additional reporting around latency percentiles and latency mean
* changed from `startDelay` to `waitThreshold`. This means a brakes instance will wait a given number of requests before checking threshold, instead of the `ms` delay it was waiting before.
* Added a `destroy` method to improve memory management and prevent memory leaks
* Added the `isOpen()` function for easier public access into the running state of the circuit breaker.

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -20,8 +20,79 @@ function getFnArgs(fn) {
...
+    rollingCountFallbackRejection: 0, // not reported
+    rollingCountFallbackSuccess: 0, // not reported
+    rollingCountResponsesFromCache: 0, // not reported
+    rollingCountSemaphoreRejected: 0, // not reported
+    rollingCountShortCircuited: 0, // not reported
+    rollingCountSuccess: stats.successful,
+    rollingCountThreadPoolRejected: 0, // not reported
+    rollingCountTimeout: stats.timedout,
+    currentConcurrentExecutionCount: 0, // not reported
+    latencyExecute_mean: 13, // todo
```
Comment (jquatier) [inline lib/utils.js]: This can be `stats.latencyMean` I believe. Also have you testes to see what the dashboard looks like (if it loads) with the amount of stuff that isn't reported in this stream?

Comment (awolden) [inline lib/utils.js]: You are right that line has been fixed.

I tested it with the hystrix-dashboard docker (https://github.com/mlabouardy/hystrix-dashboard-docker)

hystrix

File: lib/Stats.js [hunk 2]
```diff
@@ -176,6 +178,12 @@ class Stats extends EventEmitter {
     this._update();
   }
 
+  /* Register a success */
```
Comment (jquatier) [inline lib/Stats.js]: wrong comment :)

**Comment by sveisvei** [comment]
Just have to say good job 👍
